### ISSUE TITLE
the example dataset are broken

### ISSUE THREAD

**Issue by Supriyadi-ID** [spark-brc/QSWATMOD2-plugin#11]
Hello, Can we use this tool to estimate groundwater levels over a specific time range? For example, for the next 3-5 years?

the example dataset in Input section (https://github.com/spark-brc/QSWATMOD2-plugin/tree/main/Inputs) are broken. Please update with the new ones. Thankyou.

**Comment by spark-brc** [comment]
Hello,

Certainly, if you have weather data suitable for the SWAT model, you can simulate groundwater levels for a specified time period. You have the option to download the input zip file by clicking the button, or you can directly access the download link here: https://github.com/spark-brc/QSWATMOD2-plugin/raw/main/Inputs/ExampleDataset.zip.
