### ISSUE TITLE
QSWATMOD Tutorial Document was valid. I really want to download it to learn QSWATMOD. Waiting for your anwser. Thank you! 

### ISSUE THREAD

**Issue by Jarofblue** [spark-brc/QSWATMOD2-plugin#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by spark-brc** [comment]
You can download the manual by clicking the button.
![image](https://github.com/spark-brc/QSWATMOD2-plugin/assets/17608997/4c393530-4aa6-40cc-aac1-183a1d8d5f20)

Also, you can click the link below.
https://github.com/spark-brc/QSWATMOD2-plugin/raw/main/docs/QSWATMOD_tutorial.pdf
