### ISSUE TITLE
Couldn't load plugin 'QSWATMOD2' due to an error when calling its classFactory() method   AttributeError: module 'numpy' has no attribute 'float' 

### ISSUE THREAD

**Issue by liorange523** [spark-brc/QSWATMOD2-plugin#6]
Hello sir, sorry to bother you. But I do run into a problem that is hard to solve.
In the discussion you replied to before, there was a problem that the versions of QSWATMOD and QGIS did not match, but I am using the latest version of QGIS3.32 and QSWATMOD2, and this problem still occurs when installing the plug-in. How can I solve this problem?

**Comment by liorange523** [comment]
Do I need to install QSWAT before installing QSWATMOD?

**Comment by spark-brc** [comment]
This has been fixed on the hotfix branch and merged to main (https://github.com/spark-brc/qswatmod/pull/1).
I've tested it with the latest version 3.32 and long-term release version (3.28 LTR) without any issues.
